#region 版本号统一管理 🔢

[versions]
# android offical libs version
com-android-application = "8.1.0-alpha11"# Android Studio Gradle Plugin 版本号
appcompat = "1.6.1"
core-ktx = "1.9.0"
fragment-ktx = "1.5.6"
activity-ktx = "1.7.0"
material = "1.8.0"
constraintlayout = "2.1.4"
recyclerview = "1.3.0"
swiperefreshlayoug = "1.1.0"
# Jetpack Components libs version
lifecycle-ktx = "2.6.1"
navigation-fragment-ktx = "2.5.3"
navigation-ui-ktx = "2.5.3"
room-ktx = "2.5.1"
paging-ktx = "3.1.1"
work-ktx = "2.8.1"

# jetbrainds offical libs version
org-jetbrains-kotlin-android = "1.8.20"
coroutines = "1.6.4"

# 常用知名开源库
hilt-android = "2.44"
retrofit = "2.9.0"
okhttp = "4.10.0"
gson = "2.10"
mmkv = "1.2.15"
coil = "2.3.0"



# test libs version
junit = "4.13.2"
androidx-test-ext-junit = "1.1.5"
espresso-core = "3.5.1"

#endregion

# region 定义依赖库 🚀

[libraries]
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext-junit" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigation-fragment-ktx" }
navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigation-ui-ktx" }

# endregion

# region 项目工程kts配置插件plugin 🍵

[plugins]
com-android-application = { id = "com.android.application", version.ref = "com-android-application" }
org-jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "org-jetbrains-kotlin-android" }

# endregion

#region 多个依赖库组成依赖包 🎒

[bundles]

#endregion

